title: RESOUND Homepage
page-top-title: Revealing Sound Driven Avian Barriers in Urbanized Landscapes
top-section-bg-text: Soundscape Ecology
home-subtitle: RESOUND Project&ensp;|&ensp;Urban Ecology & Acoustics
copyright-text: '&copy; Magaranth Rajkumar RESOUND Project 2025-2026. All Rights Reserved.'
